apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pelias-data
  labels:
    app.kubernetes.io/part-of: pelias
    app.kubernetes.io/component: storage
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: pitt-vcf-vks-storage-policy
  resources:
    requests:
      storage: 50Gi
