apiVersion: batch/v1
kind: Job
metadata:
  name: pelias-schema-drop
  labels:
    app.kubernetes.io/part-of: pelias
    app.kubernetes.io/component: ops
  annotations: {}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: pelias
        app.kubernetes.io/component: build
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: pelias-schema-drop
        image: pelias/schema:master
        command:
        - sh
        - -c
        - node scripts/drop_index || true
        env:
        - name: PELIAS_CONFIG
          value: /code/pelias.json
        volumeMounts:
        - name: config
          mountPath: /code/pelias.json
          subPath: pelias.json
          readOnly: true
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: pelias-config
