apiVersion: v1
kind: ResourceQuota
metadata:
  name: api
  labels:
    app.kubernetes.io/part-of: pelias
    app.kubernetes.io/component: serve
  annotations:
    argocd.argoproj.io/sync-wave: '11'
spec:
  hard:
    requests.cpu: '2'
    requests.memory: 12Gi
